### ISSUE TITLE
set log OFF ?

### ISSUE THREAD

**Issue by tissatussa** [frankkopp/FrankyGo#40]
hi,

when using the -h (help) parameter, i read :

```
  -loglvl string
        standard log level
        (critical|error|warning|notice|info|debug)
```

it's not clear to me what these different levels do.
i also discovered (by text-search in the source files) a log level "off" exists, and that's what i want : no logging.
but it doesn't work :

`$ ./FrankyGo -loglvl off`

this runs FrankyGo fine (in terminal and eg. in CuteChess) but it's still logging ..
what's wrong ?
(i'm on Xubuntu 20.04)

**Comment by frankkopp** [comment]
Thanks for your message. 
I'm not actively developing this any further. It served its purpose as a Go learning exercise.
You can fork it any time and develop it further.
